Feature/letter box
nnnkate/Wordle pull request #2
Opened 2022-04-25 21:30 UTC by nnnkate

Сreated a feature branch for git flow

2022-04-26 20:38 UTC, nnnkate commented
@dashaGurinovich Uploaded the keyboard feature to the letter box branch because letter box is not yet approved.

2022-04-26 20:47 UTC, nnnkate commented
@dashaGurinovich if you don't mind, I made letters on the keyboard as struct LetterBox  the "delete" button also inherits UIButton class (but with its own functionality)
and the "enter" button will be separately at the bottom of the screen (as in the application that I showed you)
it will display "submit"/"not a word"

2022-04-26 21:04 UTC, nnnkate commented
@dashaGurinovich And one more question, sorry.
Is it possible in my case to use the "factory method" pattern to create a LetterBox and a KeyboardButton?
Is it appropriate?
These classes have so much in common, maybe they should conform to a common protocol...
And with the extension we can implement some methods of these classes...
Do it, may I?

2022-04-27 22:21 UTC, dashaGurinovich commented
> 

Do you want to create separate "factory methods" for the LetterBox and the KeyboardButton or one common method for both?

Yes, you can create a common protocol for them. You just need to distinguish the common properties and methods for them. Maybe we should discuss it on the lesson because we are going to learn protocols this lesson?

2022-04-27 22:37 UTC, dashaGurinovich approved these changes
Good work! Well done! Just a couple of possible improvements

2022-04-27 22:37 UTC, dashaGurinovich commented on Wordle/Extensions/UIKit/UIView+Extension.swift
> +    }
We should an empty space here between the functions

2022-04-27 22:37 UTC, dashaGurinovich commented on Wordle/Models/KeyboardManager.swift
> +        }
Maybe I would have put it in one line because it's pretty long and nothing complex is happening here

2022-04-27 22:37 UTC, dashaGurinovich commented on Wordle/Views/Base.lproj/Main.storyboard
> +        <!--View Controller-->
Aren't your `Keyboard Container` missing constraints to the parent view? As I understand the `Keyboard Container` should be the same height and width as the parent view. But adding these constraints will conflict with the `proportional height` constraint in the parent view. Maybe we need to discuss the logic of how you want to handle the keyboard size so I can help you with the constraints here

2022-04-27 22:37 UTC, dashaGurinovich commented on Wordle/Views/Keyboard/DeleteButtonView.swift
> +class DeleteButtonView: UIButton {
`DeleteButtonView` and `KeyboardButtonView` (maybe you should rename it to `CharacterKeyboardButton`?) have similar code. I suggest you create a view called `BaseKeyboardButton` where you put these similar properties and methods and inherit `DeleteButtonView` and `KeyboardButtonView` from it. If you want to change the UI of the keyboard latter you will change it only in the  `BaseKeyboardButton`

2022-04-28 03:32 UTC, nnnkate commented
> Do you want to create separate "factory methods" for the LetterBox and the KeyboardButton or one common method for both?
> 
> Yes, you can create a common protocol for them. You just need to distinguish the common properties and methods for them. Maybe we should discuss it on the lesson because we are going to learn protocols this lesson?

About "factory method" I mean something like this:
https://refactoring.guru/ru/design-patterns/factory-method/swift/example#example-1
Something that creates new objects without using the LetterBox and the KeyboardButton classes

Ok, then I'll leave it until the discussion in the lesson

2022-04-28 03:37 UTC, nnnkate commented on Wordle/Views/Base.lproj/Main.storyboard
> +        <!--View Controller-->
Ok, that would be awesome

2022-05-11 19:06 UTC, dashaGurinovich requested changes
Good work! Very solid code! It looks great! We just need to make it more suitable for the MVC and we're good to go

2022-05-11 19:06 UTC, darya-gurinovich commented on Wordle/Delegates/Keyboard/KeyboardButtonDelegate.swift
> +    func checkWordButtonTap()
Maybe we can improve naming adding `handle` to the beginning of these methods? For example, `handleDeleteButtonTap()`

2022-05-11 19:06 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +    }
Why do we need these methods? I believe we would set these parameters only in the `init` so we can just set these properties there. If you use methods here, your properties would need to be initialised before calling these methods in the init. You should create such methods only if there's more functionality other than just setting a value

2022-05-11 19:06 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +            return }
The `}` should be on the next line

2022-05-11 19:06 UTC, darya-gurinovich commented on Wordle/ViewControllers/GameViewController.swift
> +    }
All of this logic should be implemented in the `GameManager`. View controller should just update views with a model result

2022-05-11 19:06 UTC, dashaGurinovich commented on Wordle/ViewControllers/GameViewController.swift
> +        }
This logic should be moved inside `WordContainer`

2022-05-11 19:06 UTC, darya-gurinovich commented on Wordle/Views/LetterBox/WordContainerView.swift
> +final class WordContainerView: UIStackView {
This name confuses a bit. I thought it was a container for a single word not for several words. It's better to rename it to `WordsContainerView`

2022-05-11 19:12 UTC, dashaGurinovich commented
@nnnkate Please, remove the unused files so they won't be shown in the project

<img width="255" alt="Screenshot 2022-05-11 at 21 52 52" src="https://user-images.githubusercontent.com/25828050/167927610-68330960-da0a-4eca-93b3-5f06adbdf21c.png">

2022-05-26 15:14 UTC, darya-gurinovich requested changes
Good work! Well done! Very solid code! Please, check your leaderboard and we're good to go

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Extensions/Int+Extension.swift
> +        let minutes = Swift.max(timerCounter / 60, 0)
Why do you need to use `max` if `timerCounter` should always be positive?

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Extensions/Int+Extension.swift
> +        return String("\(hours):\(String(format: "%02d", minutes)):\(String(format: "%02d", timerCounter))")
I believe the outer `String()` is absolute

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +        if UserDefaultsService.shared.decodeObject(type: Bool.self, for: .hardMode) ?? false {
You shouldn't use `decodeObject` for `Bool` because user defaults has a built-in function for `Bool`. You should just create such method in `UserDefaultsService`

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +    }
Where do you use this function? If it's not used, it's better to remove it

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +    // MARK: -Timer
You should add a space between `-` and `Timer`

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +        }
Please, fix the tabulation

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +            updateLeadersBoard()
Do you want to update the leaderboard even if a user has lost?

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +    (UserDefaultsService.shared.decodeObject(type: [String: GameResult].self, for: .leadersBoard) ?? [String: GameResult]()).map{ ($0.key, $0.value) }
I would have moved this logic into a separate function and created property like this: `lazy var leadersBoardData: [(String, GameResult)] = function()`

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +                           forCellReuseIdentifier: LeadersBoardTableViewCell.id)
`forCellReuseIdentifier` should be under `UINib`

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +        super.viewDidLoad()
I'm not able to see anything. Please, check

![Simulator Screen Shot - iPhone 13 - 2022-05-26 at 18 09 58](https://user-images.githubusercontent.com/25828050/170517410-daa2e42f-cc0d-4f64-969a-3f38bb27cd06.png)

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +    }
You can drop this code because it's a default value

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +        super.viewDidLoad()
I would suggest to make your table background transparent

2022-05-26 15:14 UTC, darya-gurinovich commented on Wordle/ViewControllers/MainMenu/MainMenuViewController.swift
> +            .instantiateViewController(withIdentifier: "settingsVC") as? SettingsViewController {
There's no need to cast these view controllers to their type because you don't use it anywhere here

2022-06-10 10:13 UTC, nnnkate commented
@dashaGurinovich check my changes please)

2022-06-13 14:39 UTC, darya-gurinovich approved these changes
Good work! Just a couple of possible improvements

2022-06-13 14:39 UTC, darya-gurinovich commented on Wordle/Models/Game/GameManager.swift
> +            timer.invalidate()
This line should be one tab to the left

2022-06-13 14:39 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +    lazy var leadersBoardData: [(String, GameResult)] = { uploadLeadersBoardData()
No need for `{}()`: `lazy var leadersBoardData: [(String, GameResult)] = uploadLeadersBoardData()`

2022-06-13 14:39 UTC, darya-gurinovich commented on Wordle/ViewControllers/LeadersBoard/LeadersBoardViewController.swift
> +                                   forCellReuseIdentifier: LeadersBoardTableViewCell.id)
You can move this code to a separate function

2022-06-13 14:39 UTC, darya-gurinovich commented on Wordle/Views/MainMenu/MainMenuButtonView.swift
> +class MainMenuButtonView: UIButton {
As this class is a button, no need to add `View` at the end of the name: `MainMenuButton`

2022-06-13 14:39 UTC, darya-gurinovich commented on Wordle/ViewControllers/Settings/SettingsViewController.swift
> +        userNameTextField.text = UserDefaultsService.shared.decodeObject(type: String.self, for: .userName) ?? ""
You still use `encodeObject` and `decodeObject` for `Bool` and `String` here. Please, create functions in `UserDefaultsService` that wrap the standard `UserDefaults` functions that work with `String` and `Bool` and use them here

2022-06-13 16:58 UTC, merged